name: Generate Snake Game from Contributions
on:
  schedule:
    - cron: "0 */12 * * *" # har 12 soatda ishlaydi
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: <TulqinUrinov>
          outputs: dist/snake.svg

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
